import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import "./draw-control.css";
import "./custom-drawing.css";
import Providers from '@/lib/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ethiopia Climate Dashboard',
  description: 'Generated by create next app',
  // Use an existing map-like SVG as the favicon
  icons: {
    icon: '/globe.svg',
    shortcut: '/globe.svg',
    apple: '/globe.svg',
  },
};

/**
 * RootLayout wraps the entire app.
 * - Loads global styles (including Leaflet draw CSS overrides)
 * - Injects client-side providers (React Query)
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* This will ensure the Leaflet Draw styles are loaded on the client side */}
        <link rel="stylesheet" href="https://unpkg.com/leaflet-draw@1.0.4/dist/leaflet.draw.css" />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}